application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "super secret here. once more. once more. once more. super secret here. once more. once more. once more."
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "rust-jobs"
  require_ssl: false
redis_uri: "redis://127.0.0.1:6379"
